// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW559RdKV3NyIjBSI-0IIbwrhah54JGeA',
    appId: '1:892500597073:web:2d32deb6925761afe69b70',
    messagingSenderId: '892500597073',
    projectId: 'fir-auth-v2-e9dff',
    authDomain: 'fir-auth-v2-e9dff.firebaseapp.com',
    storageBucket: 'fir-auth-v2-e9dff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0sWCqAoj2i6WqfPJvVYHsIemGQTzKOY',
    appId: '1:892500597073:android:d1f8e8e1f54e8446e69b70',
    messagingSenderId: '892500597073',
    projectId: 'fir-auth-v2-e9dff',
    storageBucket: 'fir-auth-v2-e9dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFAztaO33Rf-J2YIcrkRtH7npI4nzIZw',
    appId: '1:892500597073:ios:e9de0dea55fcc683e69b70',
    messagingSenderId: '892500597073',
    projectId: 'fir-auth-v2-e9dff',
    storageBucket: 'fir-auth-v2-e9dff.appspot.com',
    iosClientId: '892500597073-9s0plnq2vb7gug1ldc4q5pmbmi8ilkli.apps.googleusercontent.com',
    iosBundleId: 'com.example.cubitAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFAztaO33Rf-J2YIcrkRtH7npI4nzIZw',
    appId: '1:892500597073:ios:33169a479501e316e69b70',
    messagingSenderId: '892500597073',
    projectId: 'fir-auth-v2-e9dff',
    storageBucket: 'fir-auth-v2-e9dff.appspot.com',
    iosClientId: '892500597073-693krcv09tc4hvlr4tkcbm9103cc5b6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cubitAuth.RunnerTests',
  );
}
